server:
  context-path: /king
  port: 8080

spring:
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  datasource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.jdbc.Driver
#      password: 4J1ttjoFX!
#      url: jdbc:mysql://192.168.1.113:3306/wms_center_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&tinyInt1isBit=false
#      username: newsitetest

      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      password: '0000'
      url: jdbc:mysql://127.0.0.1:3306/bs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&tinyInt1isBit=false
      username: huanjian

      #连接池配置
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      logSlowSql: true
  mail:
    host: smtp.qq.com
    username: 632669794@qq.com
    password: dfrzliqeszjmbehe
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: false
            required: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ahuthj.model

# 配置pageHelper分页插件的内容
pagehelper:
     helperDialect: mysql
     reasonable: true
     supportMethodsArguments: true
     params: count=countSq


logging:
    config:
        classpath: log4j2-spring.xml

# 配置文件，通过 @Value("${com.email}") 引用
com.email: ahuthj@163.com