server:
  context-path: /king
  port: 8080

spring:
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      password: 4J1ttjoFX!
      url: jdbc:mysql://192.168.1.113:3306/seUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&tinyInt1isBit=false
      username: newsitetest
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ahuthj.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
    config:
        classpath: log4j2-spring.xml

# 配置文件，通过 @Value("${com.email}") 引用
com.email: ahuthj@163.com